version: '3'

services:

  dwn-server:
    container_name: dwn-server
    image: ghcr.io/tbd54566975/dwn-server:main
    ports:
      - ${DWN_SERVER_PORT:-3000}:3000
    volumes:
      - ./dwn-server:/dwn-server/data
